#!/usr/bin/env bash

aws ecr create-repository --repository-name test/myapp --image-tag-mutability MUTABLE && true

cd ./services/web

TAG=$1

docker build -t test/myapp:$TAG .

docker tag test/myapp:$TAG  01234567890.dkr.ecr.us-west-2.amazonaws.com/test/myapp:$TAG

aws --region us-west-2 ecr get-login-password | docker login --username AWS --password-stdin 01234567890.dkr.ecr.us-west-2.amazonaws.com

docker push 01234567890.dkr.ecr.us-west-2.amazonaws.com/test/myapp:$TAG

printf "\naws ecr list-images\n"
aws ecr list-images --repository-name test/myapp --profile AmazonEC2ContainerRegistryReadOnly | grep 'imageTag' | awk -F ":" '{print $2}' | sed 's/"//g; s/,//g' | sort -f -t . -k 1,1 -k 2,2n -k 3,3n -k 4,4n | tail -5; printf "\n"

cd -
